name: Fullstack Test Job

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Change directory to client
      run: cd client
    - run: npm ci
    - run: npm run lint